apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: christophersesugh/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: christophersesugh/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "app/**/*.ts"
            dest: .
    - image: christophersesugh/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

  local:
    push: false

manifests:
  rawYaml:
    - infra/k8s/*
